causeRecode39Headers = [
  "Tuberculosis",
  "Syphilis",
  "HIV",
  "Malignant Neoplasm Unspecified",
  "Malignant Neoplasm of Stomach",
  "Malignant Neoplasm of Colon or Rectum or Anus",
  "Malignant Neoplasm of Pancreas",
  "Malignant Neoplasm of Trachea or Bronchus or Lung",
  "Malignant Neoplasm of Breast",
  "Malignant Neoplasm of Cervix or Uteri or Corpus Uteri or Ovary",
  "Malignant Neoplasm of Prostate",
  "Malignant Neoplasm of Urinary Tract",
  "Non Hodgkins Lymphoma",
  "Leukemia",
  "Other Malignant Neoplasms",
  "Diabetes Mellitus",
  "Alzheimers Disease",
  "Major Cardiovascular Diseases Unspecified",
  "Diseases of Heart",
  "Hypertensive Heart Disease with or without Renal Disease",
  "Ischemic Heart Diseases",
  "Other Diseases of Heart",
  "Essential Primary Hypertension or Hypertensive Renal Disease",
  "Cerebrovascular Diseases",
  "Atherosclerosis",
  "Other Diseases of Circulatory System",
  "Influenza or Pneumonia",
  "Chronic Lower Respiratory Diseases",
  "Peptic Ulcer",
  "Chronic Liver Disease or Cirrhosis",
  "Nephritis or Nephrotic Syndrome or Nephrosis",
  "Pregnancy or Childbirth or the Puerperium",
  "Certain Conditions Originating in the Perinatal Period",
  "Congenital Malformations or Deformations or and Chromosomal Abnormalities",
  "Sudden Infant Death Syndrome",
  "Symptoms and Signs and Abnormal Clinical " +
  "and Laboratory Findings that are not Elsewhere Classified",
  "All Other Diseases Residual",
  "Motor Vehicle Accidents",
  "All Other and Unspecified Accidents and Adverse Effects",
  "Intentional Self Harm Suicide",
  "Assault Homicide",
  "All Other External Causes"
]

mannerOfDeathHeaders = [
  "Accident",
  "Suicide",
  "Homicide",
  "Pending Investigation",
  "Could Not Determine",
  "Self Inflicted",
  "Natural"
]
